name: AntiBlockFade
version: 1.0.0
main: org.keelfy.antifade.AntiBlockFadePlugin
api-version: '1.21'
commands:
  antiblockfade:
    description: Toggles plugin
    usage: /<command> <true|false>
    permission: antiBlockFade.toggle

permissions:
  antiBlockFade.toggle:
    description: Allows toggling the block fade prevention feature.
    default: op